/* Generated by tools/gen_bindings.py from the PivotKit RE database.
 * Target: Pivot Animator 5.2.11 (sha256 2c7911d3303cc28d...).
 * DO NOT EDIT BY HAND - edit the database/research and regenerate. */
#ifndef PIVOT_5_2_11_BINDINGS_H
#define PIVOT_5_2_11_BINDINGS_H
#include <stdint.h>

#define PIVOT_IMAGE_BASE 0x400000u

typedef struct PkRect   { int32_t l, t, r, b; } PkRect;
typedef struct PkRectF  { float   l, t, r, b; } PkRectF;
typedef struct PkPoint  { float   x, y; } PkPoint;
/* TCamera (GlobalTypes) - exact member layout TBD */
typedef struct PkCamera { PkPoint pos; float angle; } PkCamera;
/* TAttachment (GlobalTypes) - 6 bytes; exact layout TBD */
typedef struct PkAttachment { uint8_t raw[6]; } PkAttachment;
/* Delphi dynamic array: ptr-4 = length (elements), ptr-8 = refcount */
typedef struct PkDynArray { void *data; } PkDynArray;
static inline uint32_t pk_dynarray_len(const PkDynArray *a) {
    return a->data ? *(uint32_t *)((char *)a->data - 4) : 0; }

/* ---- Class registry (VMT addresses, instance sizes) ---- */
typedef struct PkClassInfo {
    const char *name;
    const char *unit;
    const char *parent;
    uint32_t    vmt_va;
    uint32_t    instance_size;
} PkClassInfo;

static const PkClassInfo PkClasses[] = {
    { "TAVICompressor", "AVICompression", "TObject", 0xADB5FCu, 0x20u },
    { "TBackgroundColorForm", "BackgroundColorUnit", "TForm", 0xA6DFB8u, 0x35Cu },
    { "TSelectionPointCol", "BackgroundColorUnit", "TSelectionPoint", 0xA6DB98u, 0x3DCu },
    { "TColorForm", "ColorUnit", "TForm", 0xA62344u, 0x474u },
    { "TFigureBuilderForm", "FigureBuilderUnit", "TForm", 0xB02CFCu, 0x73Cu },
    { "TFigureType", "FigureTypeUnit", "TObject", 0xAF97A4u, 0x3Cu },
    { "TFigure", "FigureUnit", "TObject", 0x93AA04u, 0x64u },
    { "TFigures", "FiguresUnit", "TObject", 0x946D9Cu, 0x54u },
    { "TImageSelector", "ImageSelector", "TVertScrollBox", 0x931818u, 0x494u },
    { "TLabelBack", "LabelBackUnit", "TLabel", 0xA6C5A0u, 0x42Cu },
    { "TMainForm", "MainUnit", "TForm", 0xB14D68u, 0x724u },
    { "TMultiLang", "MultiLanguage", "TObject", 0xAE4860u, 0x18u },
    { "TPivotText", "PivotTextUnit", "TObject", 0x937A2Cu, 0x28u },
    { "TPlayer", "PlayerUnit", "TObject", 0x950E74u, 0x60u },
    { "TIdxPolygon", "PolygonUnit", "TObject", 0x92FCA4u, 0x18u },
    { "TSprite", "SpriteUnit", "TObject", 0xAF6A94u, 0x34u },
    { "TThreadedTimer", "ThreadedTimer", "TComponent", 0x951918u, 0x6Cu },
    { "TTrackBarLabel", "TrackBarLabelUnit", "TTrackBar", 0xA6D010u, 0x444u },
    { "TVideoForm", "VideoUnit", "TForm", 0xADC3E0u, 0x384u },
    { "TQueueThread", "WavePlay", "TThread", 0xA9CC2Cu, 0x34u },
    { "TWavePlayer", "WavePlay", "TObject", 0xA9CE0Cu, 0x44u },
    { "TWinBitmap", "WinBitmap", "TObject", 0x9201B4u, 0x8u },
    { "TZoomImage", "ZoomImageUnit", "TImage", 0x9345F4u, 0x45Cu },
};
#define PkClassCount (sizeof(PkClasses)/sizeof(PkClasses[0]))

/* ---- Structs for classes with init-table field maps ---- */
/* TFigureType (FigureTypeUnit) - VMT 0xAF97A4, size 0x3C */
typedef struct TFigureTypeS {
    uint32_t vmt; /* +0x00 */
    uint32_t FNumSegments; /* +0x4 : Integer */
    uint32_t FNumPolygons; /* +0x6 : Integer */
    PkDynArray Vertices; /* +0x8 : TArray<TVertex> */
    PkDynArray Segments; /* +0xC : DynArray::TFigureType.:2 */
    PkDynArray SegImages; /* +0x10 : DynArray::TFigureType.:3 */
    PkDynArray Polygons; /* +0x14 : DynArray::TFigureType.:4 */
    PkDynArray Text; /* +0x18 : DynArray::TFigureType.:5 */
    PkDynArray DrawOrder; /* +0x1C : DynArray::TFigureType.:6 */
    uint32_t Used; /* +0x20 : Integer */
    uint8_t IsSingleColor; /* +0x22 : Boolean */
    uint8_t _pad_23[0x24 - 0x23];
    uint32_t SingleColor; /* +0x24 : Integer */
    float OutlineThickness; /* +0x28 : Float:Single */
    uint32_t OutlineColor; /* +0x2C : Integer */
    uint32_t OutlineTransparency; /* +0x30 : Integer */
    PkDynArray Correspondence; /* +0x34 : DynArray:TArrayOfWord */
    uint8_t _tail[4];
} TFigureTypeS;

/* TFigure (FigureUnit) - VMT 0x93AA04, size 0x64 */
typedef struct TFigureS {
    uint32_t vmt; /* +0x00 */
    PkRect FExtent; /* +0x4 : record TRect */
    PkRectF FExtentF; /* +0x14 : record TRectF */
    uint32_t FColor; /* +0x24 : Integer */
    uint32_t FTrans; /* +0x28 : Integer */
    float FScale; /* +0x2C : Float:Single */
    uint32_t FFigureType; /* +0x30 : Integer */
    PkDynArray FigVertices; /* +0x34 : TArray<TFigVertex> */
    PkDynArray FigSegments; /* +0x38 : DynArray:TFigSegments */
    uint8_t Flipped; /* +0x3C : Boolean */
    uint8_t _pad_3D[0x3E - 0x3D];
    uint32_t NumSegVarLen; /* +0x3E : Integer */
    uint32_t NumSegVarBend; /* +0x40 : Integer */
    PkAttachment Attachment; /* +0x42 : record TAttachment */
    uint32_t NumSegAttach; /* +0x48 : Integer */
    uint8_t CanAttach; /* +0x4A : Boolean */
    uint8_t _pad_4B[0x4C - 0x4B];
    uint32_t DrawOrderIdx; /* +0x4C : Integer */
    uint32_t Selected; /* +0x50 : Integer */
    uint8_t InSelectBox; /* +0x54 : Boolean */
    uint8_t Moved; /* +0x55 : Boolean */
    uint8_t _pad_56[0x58 - 0x56];
    uint32_t ID; /* +0x58 : Integer */
    uint32_t Next; /* +0x5C : Integer */
    uint32_t Prev; /* +0x5E : Integer */
    uint8_t _tail[2];
} TFigureS;

/* TFigures (FiguresUnit) - VMT 0x946D9C, size 0x54 */
typedef struct TFiguresS {
    uint32_t vmt; /* +0x00 */
    uint32_t FNumFigures; /* +0x4 : Integer */
    uint32_t FBackground; /* +0x6 : Integer */
    uint32_t FBackground2; /* +0x8 : Integer */
    uint32_t FBackgroundRatio; /* +0xA : Integer */
    uint32_t FFrameTween; /* +0xC : Integer */
    PkDynArray Figures; /* +0x10 : DynArray::TFigures.:1 */
    PkDynArray DrawOrder; /* +0x14 : DynArray:TArrayOfWord */
    uint8_t FrameSelected; /* +0x18 : Boolean */
    uint8_t StartedAttaching; /* +0x19 : Boolean */
    uint8_t _pad_1A[0x1C - 0x1A];
    PkDynArray EditSelected; /* +0x1C : DynArray:TArrayOfWord */
    uint32_t NumSelected; /* +0x20 : Integer */
    PkRectF SelectedRect; /* +0x24 : record TRectF */
    uint8_t _pad_34[0x38 - 0x34];
    PkCamera Camera; /* +0x38 : record TCamera */
    uint8_t _tail[16];
} TFiguresS;

/* TImageSelector (ImageSelector) - VMT 0x931818, size 0x494 */
typedef struct TImageSelectorS {
    uint32_t vmt; /* +0x00 */
    uint8_t _pad_4[0x450 - 0x4];
    PkDynArray Images; /* +0x450 : DynArray::TImageSelector.:1 */
    PkDynArray Labels; /* +0x454 : DynArray::TImageSelector.:2 */
    PkDynArray Infos; /* +0x458 : TArray<string> */
    uint32_t FCount; /* +0x45C : Integer */
    uint32_t FWidth; /* +0x460 : Integer */
    uint32_t NumX; /* +0x464 : Integer */
    uint32_t NumY; /* +0x468 : Integer */
    uint32_t TextHeight; /* +0x46C : Integer */
    uint32_t TotalHeight; /* +0x470 : Integer */
    uint32_t TotalWidth; /* +0x474 : Integer */
    uint8_t DisableDraw; /* +0x478 : Boolean */
    uint8_t _pad_479[0x47C - 0x479];
    uint32_t FSearch; /* +0x47C : string */
    PkDynArray Regions; /* +0x480 : DynArray::TImageSelector.:4 */
    PkRect SelectBox; /* +0x484 : class TRectangle */
    float ImageAspect; /* +0x488 : Float:Single */
    uint8_t _tail[8];
} TImageSelectorS;

/* TMultiLang (MultiLanguage) - VMT 0xAE4860, size 0x18 */
typedef struct TMultiLangS {
    uint32_t vmt; /* +0x00 */
    uint32_t Def; /* +0x4 : class TStrings */
    uint32_t Phrases; /* +0x8 : class TStrings */
    uint32_t LangPath; /* +0xC : string */
    uint32_t Lang; /* +0x10 : string */
    uint8_t _tail[4];
} TMultiLangS;

/* TPivotText (PivotTextUnit) - VMT 0x937A2C, size 0x28 */
typedef struct TPivotTextS {
    uint32_t vmt; /* +0x00 */
    PkDynArray FChars; /* +0x4 : DynArray::TPivotText.:1 */
    PkDynArray FPaths; /* +0x8 : DynArray::TPivotText.:2 */
    uint32_t FPathCount; /* +0xC : Integer */
    PkRectF FExtent; /* +0x10 : record TRectF */
    uint32_t Layout; /* +0x20 : class TTextLayout */
    uint8_t _tail[4];
} TPivotTextS;

/* TIdxPolygon (PolygonUnit) - VMT 0x92FCA4, size 0x18 */
typedef struct TIdxPolygonS {
    uint32_t vmt; /* +0x00 */
    uint32_t FColor; /* +0x4 : Integer */
    uint32_t FTransparency; /* +0x8 : Integer */
    uint32_t FNumVertices; /* +0xA : Integer */
    PkDynArray VertexIdx; /* +0xC : DynArray::TIdxPolygon.:1 */
    uint32_t DrawOrderIdx; /* +0x10 : Integer */
    uint8_t _tail[4];
} TIdxPolygonS;

/* TTrackBarLabel (TrackBarLabelUnit) - VMT 0xA6D010, size 0x444 */
typedef struct TTrackBarLabelS {
    uint32_t vmt; /* +0x00 */
    uint8_t _pad_4[0x428 - 0x4];
    uint32_t FLabel; /* +0x428 : class TLabelBack */
    uint32_t FSuffix; /* +0x42C : string */
    uint32_t FTimer; /* +0x430 : class TTimer */
    uint32_t FOffset; /* +0x434 : Integer */
    uint32_t FValueToString; /* +0x438 : TValueToString */
    uint8_t _tail[8];
} TTrackBarLabelS;

/* TWavePlayer (WavePlay) - VMT 0xA9CE0C, size 0x44 */
typedef struct TWavePlayerS {
    uint32_t vmt; /* +0x00 */
    uint32_t FQueueThread; /* +0x4 : class TQueueThread */
    uint8_t FPaused; /* +0x8 : Boolean */
    uint8_t _pad_9[0xC - 0x9];
    uint32_t FReadBuffer; /* +0xC : TFF_AudioSpecCallback */
    uint32_t FUserData; /* +0x10 : Pointer */
    uint32_t FLastErrMsg; /* +0x14 : string */
    uint32_t FWaveHandle; /* +0x18 : Integer */
    uint32_t FWaveFormat; /* +0x1C : record tWAVEFORMATEX */
    uint8_t _pad_20[0x30 - 0x20];
    PkDynArray FWaveHdr; /* +0x30 : DynArray::TWavePlayer.:1 */
    PkDynArray FWaveBuf; /* +0x34 : DynArray::TWavePlayer.:2 */
    uint32_t FWaveBufSize; /* +0x38 : Integer */
    uint32_t FWaveBufIdx; /* +0x3C : Integer */
    uint8_t _tail[4];
} TWavePlayerS;

/* ---- Field offset macros (name -> offset, all mapped classes) ---- */
#define PK_TBackgroundColorForm_RectShow_OFF 0x2F8u
#define PK_TBackgroundColorForm_RadioButtonLinear_OFF 0x2FCu
#define PK_TBackgroundColorForm_RadioButtonRadial_OFF 0x300u
#define PK_TBackgroundColorForm_Label2_OFF 0x304u
#define PK_TBackgroundColorForm_RadioButtonSolid_OFF 0x308u
#define PK_TBackgroundColorForm_Label1_OFF 0x30Cu
#define PK_TBackgroundColorForm_RectGrid_OFF 0x310u
#define PK_TBackgroundColorForm_AddButton_OFF 0x314u
#define PK_TBackgroundColorForm_CancelButton_OFF 0x318u
#define PK_TBackgroundColorForm_ColorButton1_OFF 0x31Cu
#define PK_TBackgroundColorForm_ColorButton2_OFF 0x320u
#define PK_TBackgroundColorForm_StyleBook1_OFF 0x324u
#define PK_TBackgroundColorForm_HelpLabel_OFF 0x328u
#define PK_TBackgroundColorForm_SwapButton_OFF 0x32Cu
#define PK_TBackgroundColorForm_ImageList1_OFF 0x330u
#define PK_TColorForm_ColorPanel1_OFF 0x2F8u
#define PK_TColorForm_ColorBox1_OFF 0x2FCu
#define PK_TColorForm_HueSpinBox_OFF 0x300u
#define PK_TColorForm_StyleBook1_OFF 0x304u
#define PK_TColorForm_SatSpinBox_OFF 0x308u
#define PK_TColorForm_LumSpinBox_OFF 0x30Cu
#define PK_TColorForm_Label1_OFF 0x310u
#define PK_TColorForm_Label2_OFF 0x314u
#define PK_TColorForm_Label3_OFF 0x318u
#define PK_TColorForm_RedSpinBox_OFF 0x31Cu
#define PK_TColorForm_GreenSpinBox_OFF 0x320u
#define PK_TColorForm_BlueSpinBox_OFF 0x324u
#define PK_TColorForm_Label4_OFF 0x328u
#define PK_TColorForm_Label5_OFF 0x32Cu
#define PK_TColorForm_Label6_OFF 0x330u
#define PK_TColorForm_Label7_OFF 0x334u
#define PK_TColorForm_HexEdit_OFF 0x338u
#define PK_TColorForm_Label8_OFF 0x33Cu
#define PK_TColorForm_AddButton_OFF 0x340u
#define PK_TColorForm_OkButton_OFF 0x344u
#define PK_TColorForm_CancelButton_OFF 0x348u
#define PK_TColorForm_AlphaSpinBox_OFF 0x34Cu
#define PK_TColorForm_Label9_OFF 0x350u
#define PK_TColorForm_Label10_OFF 0x354u
#define PK_TColorForm_Label11_OFF 0x358u
#define PK_TColorForm_SelectedRect_OFF 0x35Cu
#define PK_TColorForm_PickButton_OFF 0x360u
#define PK_TColorForm_ImageList1_OFF 0x364u
#define PK_TFigureBuilderForm_Panel1_OFF 0x2F8u
#define PK_TFigureBuilderForm_ImageList1_OFF 0x2FCu
#define PK_TFigureBuilderForm_ImageListButtons_OFF 0x300u
#define PK_TFigureBuilderForm_OpenDialog1_OFF 0x304u
#define PK_TFigureBuilderForm_SaveDialog1_OFF 0x308u
#define PK_TFigureBuilderForm_MenuBar1_OFF 0x30Cu
#define PK_TFigureBuilderForm_File1_OFF 0x310u
#define PK_TFigureBuilderForm_New1_OFF 0x314u
#define PK_TFigureBuilderForm_N2_OFF 0x318u
#define PK_TFigureBuilderForm_Open1_OFF 0x31Cu
#define PK_TFigureBuilderForm_Save1_OFF 0x320u
#define PK_TFigureBuilderForm_SaveAs1_OFF 0x324u
#define PK_TFigureBuilderForm_AddToAnimation1_OFF 0x328u
#define PK_TFigureBuilderForm_EditFigureType1_OFF 0x32Cu
#define PK_TFigureBuilderForm_N6_OFF 0x330u
#define PK_TFigureBuilderForm_LoadSpriteImage1_OFF 0x334u
#define PK_TFigureBuilderForm_N1_OFF 0x338u
#define PK_TFigureBuilderForm_Exit1_OFF 0x33Cu
#define PK_TFigureBuilderForm_Edit1_OFF 0x340u
#define PK_TFigureBuilderForm_Undo1_OFF 0x344u
#define PK_TFigureBuilderForm_Redo1_OFF 0x348u
#define PK_TFigureBuilderForm_N4_OFF 0x34Cu
#define PK_TFigureBuilderForm_Transparent1_OFF 0x350u
#define PK_TFigureBuilderForm_Outlinethicknessup1_OFF 0x354u
#define PK_TFigureBuilderForm_OutlineThicknessDown1_OFF 0x358u
#define PK_TFigureBuilderForm_OutlineColour1_OFF 0x35Cu
#define PK_TFigureBuilderForm_N3_OFF 0x360u
#define PK_TFigureBuilderForm_EditMode1_OFF 0x364u
#define PK_TFigureBuilderForm_Duplicateflip1_OFF 0x368u
#define PK_TFigureBuilderForm_CircleButton_OFF 0x36Cu
#define PK_TFigureBuilderForm_StyleBook1_OFF 0x370u
#define PK_TFigureBuilderForm_LineButton_OFF 0x374u
#define PK_TFigureBuilderForm_btnPoly_OFF 0x378u
#define PK_TFigureBuilderForm_Line1_OFF 0x37Cu
#define PK_TFigureBuilderForm_ChangeKindButton_OFF 0x380u
#define PK_TFigureBuilderForm_CircleKindButton_OFF 0x384u
#define PK_TFigureBuilderForm_SplitButton_OFF 0x388u
#define PK_TFigureBuilderForm_DuplicateButton_OFF 0x38Cu
#define PK_TFigureBuilderForm_NominateButton_OFF 0x390u
#define PK_TFigureBuilderForm_ChangeStaticButton_OFF 0x394u
#define PK_TFigureBuilderForm_DeleteButton_OFF 0x398u
#define PK_TFigureBuilderForm_ColorButton_OFF 0x39Cu
#define PK_TFigureBuilderForm_btnFlip_OFF 0x3A0u
#define PK_TFigureBuilderForm_UpButton_OFF 0x3A4u
#define PK_TFigureBuilderForm_DownButton_OFF 0x3A8u
#define PK_TFigureBuilderForm_LowerButton_OFF 0x3ACu
#define PK_TFigureBuilderForm_RaiseButton_OFF 0x3B0u
#define PK_TFigureBuilderForm_HighlightTimer_OFF 0x3B4u
#define PK_TFigureBuilderForm_UpDownTimer_OFF 0x3B8u
#define PK_TFigureBuilderForm_StatusBar_OFF 0x3BCu
#define PK_TFigureBuilderForm_StatusLabel_OFF 0x3C0u
#define PK_TFigureBuilderForm_Layout1_OFF 0x3C4u
#define PK_TFigureBuilderForm_PolyRect_OFF 0x3C8u
#define PK_TFigureBuilderForm_dlgOpenPicSprite_OFF 0x3CCu
#define PK_TFigureBuilderForm_BackRectangle_OFF 0x3D0u
#define PK_TFigureBuilderForm_BorderRectangle_OFF 0x3D4u
#define PK_TFigureBuilderForm_XButton_OFF 0x3D8u
#define PK_TFigureBuilderForm_View1_OFF 0x3DCu
#define PK_TFigureBuilderForm_ZInMenuItem_OFF 0x3E0u
#define PK_TFigureBuilderForm_ZOutMenuItem_OFF 0x3E4u
#define PK_TFigureBuilderForm_Z100MenuItem_OFF 0x3E8u
#define PK_TFigureBuilderForm_Z200MenuItem_OFF 0x3ECu
#define PK_TFigureBuilderForm_Z50MenuItem_OFF 0x3F0u
#define PK_TFigureBuilderForm_ZSelMenuItem_OFF 0x3F4u
#define PK_TFigureBuilderForm_ZFigMenuItem_OFF 0x3F8u
#define PK_TFigureBuilderForm_MenuItem1_OFF 0x3FCu
#define PK_TFigureBuilderForm_ZoomLabel_OFF 0x400u
#define PK_TFigureBuilderForm_ChangeCapButton_OFF 0x404u
#define PK_TFigureBuilderForm_Gradient1_OFF 0x408u
#define PK_TFigureBuilderForm_Help1_OFF 0x40Cu
#define PK_TFigureBuilderForm_MenuItem2_OFF 0x410u
#define PK_TFigureBuilderForm_MenuItem3_OFF 0x414u
#define PK_TFigureBuilderForm_HighlightMenuItem_OFF 0x418u
#define PK_TFigureBuilderForm_SegmentInputMenuItem_OFF 0x41Cu
#define PK_TFigureBuilderForm_DoubleClickTimer_OFF 0x420u
#define PK_TFigureBuilderForm_MatchZoomMenuItem_OFF 0x424u
#define PK_TFigureBuilderForm_ImageListButtonsDM_OFF 0x428u
#define PK_TFigureBuilderForm_BackColorMenuItem_OFF 0x42Cu
#define PK_TFigureBuilderForm_PreviewMenuItem_OFF 0x430u
#define PK_TFigureBuilderForm_CaptionLabel_OFF 0x434u
#define PK_TFigureBuilderForm_EditModeRMenuItem_OFF 0x438u
#define PK_TFigureBuilderForm_ShowStaticMenuItem_OFF 0x43Cu
#define PK_TFigureType_FNumSegments_OFF 0x4u
#define PK_TFigureType_FNumPolygons_OFF 0x6u
#define PK_TFigureType_Vertices_OFF 0x8u
#define PK_TFigureType_Segments_OFF 0xCu
#define PK_TFigureType_SegImages_OFF 0x10u
#define PK_TFigureType_Polygons_OFF 0x14u
#define PK_TFigureType_Text_OFF 0x18u
#define PK_TFigureType_DrawOrder_OFF 0x1Cu
#define PK_TFigureType_Used_OFF 0x20u
#define PK_TFigureType_IsSingleColor_OFF 0x22u
#define PK_TFigureType_SingleColor_OFF 0x24u
#define PK_TFigureType_OutlineThickness_OFF 0x28u
#define PK_TFigureType_OutlineColor_OFF 0x2Cu
#define PK_TFigureType_OutlineTransparency_OFF 0x30u
#define PK_TFigureType_Correspondence_OFF 0x34u
#define PK_TFigure_FExtent_OFF 0x4u
#define PK_TFigure_FExtentF_OFF 0x14u
#define PK_TFigure_FColor_OFF 0x24u
#define PK_TFigure_FTrans_OFF 0x28u
#define PK_TFigure_FScale_OFF 0x2Cu
#define PK_TFigure_FFigureType_OFF 0x30u
#define PK_TFigure_FigVertices_OFF 0x34u
#define PK_TFigure_FigSegments_OFF 0x38u
#define PK_TFigure_Flipped_OFF 0x3Cu
#define PK_TFigure_NumSegVarLen_OFF 0x3Eu
#define PK_TFigure_NumSegVarBend_OFF 0x40u
#define PK_TFigure_Attachment_OFF 0x42u
#define PK_TFigure_NumSegAttach_OFF 0x48u
#define PK_TFigure_CanAttach_OFF 0x4Au
#define PK_TFigure_DrawOrderIdx_OFF 0x4Cu
#define PK_TFigure_Selected_OFF 0x50u
#define PK_TFigure_InSelectBox_OFF 0x54u
#define PK_TFigure_Moved_OFF 0x55u
#define PK_TFigure_ID_OFF 0x58u
#define PK_TFigure_Next_OFF 0x5Cu
#define PK_TFigure_Prev_OFF 0x5Eu
#define PK_TFigures_FNumFigures_OFF 0x4u
#define PK_TFigures_FBackground_OFF 0x6u
#define PK_TFigures_FBackground2_OFF 0x8u
#define PK_TFigures_FBackgroundRatio_OFF 0xAu
#define PK_TFigures_FFrameTween_OFF 0xCu
#define PK_TFigures_Figures_OFF 0x10u
#define PK_TFigures_DrawOrder_OFF 0x14u
#define PK_TFigures_FrameSelected_OFF 0x18u
#define PK_TFigures_StartedAttaching_OFF 0x19u
#define PK_TFigures_EditSelected_OFF 0x1Cu
#define PK_TFigures_NumSelected_OFF 0x20u
#define PK_TFigures_SelectedRect_OFF 0x24u
#define PK_TFigures_Camera_OFF 0x38u
#define PK_TImageSelector_Images_OFF 0x450u
#define PK_TImageSelector_Labels_OFF 0x454u
#define PK_TImageSelector_Infos_OFF 0x458u
#define PK_TImageSelector_FCount_OFF 0x45Cu
#define PK_TImageSelector_FWidth_OFF 0x460u
#define PK_TImageSelector_NumX_OFF 0x464u
#define PK_TImageSelector_NumY_OFF 0x468u
#define PK_TImageSelector_TextHeight_OFF 0x46Cu
#define PK_TImageSelector_TotalHeight_OFF 0x470u
#define PK_TImageSelector_TotalWidth_OFF 0x474u
#define PK_TImageSelector_DisableDraw_OFF 0x478u
#define PK_TImageSelector_FSearch_OFF 0x47Cu
#define PK_TImageSelector_Regions_OFF 0x480u
#define PK_TImageSelector_SelectBox_OFF 0x484u
#define PK_TImageSelector_ImageAspect_OFF 0x488u
#define PK_TMainForm_MainMenu1_OFF 0x2F8u
#define PK_TMainForm_File1_OFF 0x2FCu
#define PK_TMainForm_Panel1_OFF 0x300u
#define PK_TMainForm_SelFigPanel_OFF 0x304u
#define PK_TMainForm_ImageList1_OFF 0x308u
#define PK_TMainForm_Edit1_OFF 0x30Cu
#define PK_TMainForm_New1_OFF 0x310u
#define PK_TMainForm_OpenAnimation1_OFF 0x314u
#define PK_TMainForm_Save1_OFF 0x318u
#define PK_TMainForm_SaveAs1_OFF 0x31Cu
#define PK_TMainForm_Export1_OFF 0x320u
#define PK_TMainForm_AnimatedGif1_OFF 0x324u
#define PK_TMainForm_Video1_OFF 0x328u
#define PK_TMainForm_SeparateImages1_OFF 0x32Cu
#define PK_TMainForm_N1_OFF 0x330u
#define PK_TMainForm_LoadBackground1_OFF 0x334u
#define PK_TMainForm_LoadSprite1_OFF 0x338u
#define PK_TMainForm_N3_OFF 0x33Cu
#define PK_TMainForm_LoadFigure1_OFF 0x340u
#define PK_TMainForm_CreateFigureType1_OFF 0x344u
#define PK_TMainForm_N2_OFF 0x348u
#define PK_TMainForm_Exit1_OFF 0x34Cu
#define PK_TMainForm_Help1_OFF 0x350u
#define PK_TMainForm_SVG1_OFF 0x354u
#define PK_TMainForm_SVGnohandles1_OFF 0x358u
#define PK_TMainForm_Deletefiguresoutsidearea1_OFF 0x35Cu
#define PK_TMainForm_BatchLoadSave1_OFF 0x360u
#define PK_TMainForm_Undo1_OFF 0x364u
#define PK_TMainForm_Redo1_OFF 0x368u
#define PK_TMainForm_N5_OFF 0x36Cu
#define PK_TMainForm_SelectAll1_OFF 0x370u
#define PK_TMainForm_DuplicateFigures1_OFF 0x374u
#define PK_TMainForm_EditJoinedFigures1_OFF 0x378u
#define PK_TMainForm_N6_OFF 0x37Cu
#define PK_TMainForm_TweenToTimeline_OFF 0x380u
#define PK_TMainForm_N4_OFF 0x384u
#define PK_TMainForm_DeleteFrames1_OFF 0x388u
#define PK_TMainForm_CopyFrames1_OFF 0x38Cu
#define PK_TMainForm_PasteFrames1_OFF 0x390u
#define PK_TMainForm_N7_OFF 0x394u
#define PK_TMainForm_Options1_OFF 0x398u
#define PK_TMainForm_PivotHelp1_OFF 0x39Cu
#define PK_TMainForm_ViewReadMeFile1_OFF 0x3A0u
#define PK_TMainForm_About1_OFF 0x3A4u
#define PK_TMainForm_FrameLabel_OFF 0x3A8u
#define PK_TMainForm_TweenLabel_OFF 0x3ACu
#define PK_TMainForm_TweenSpinEdit_OFF 0x3B0u
#define PK_TMainForm_SelectedGroupBox_OFF 0x3B4u
#define PK_TMainForm_GroupBox2_OFF 0x3B8u
#define PK_TMainForm_BackgroundButton_OFF 0x3BCu
#define PK_TMainForm_AddFigureButton_OFF 0x3C0u
#define PK_TMainForm_NextFrameButton_OFF 0x3C4u
#define PK_TMainForm_EditTypeButton_OFF 0x3C8u
#define PK_TMainForm_DeleteFigureButton_OFF 0x3CCu
#define PK_TMainForm_CenterButton_OFF 0x3D0u
#define PK_TMainForm_FlipButton_OFF 0x3D4u
#define PK_TMainForm_DeleteSelFrameButton_OFF 0x3D8u
#define PK_TMainForm_ColorButton_OFF 0x3DCu
#define PK_TMainForm_ColorRectangle_OFF 0x3E0u
#define PK_TMainForm_JoinButton_OFF 0x3E4u
#define PK_TMainForm_FrontButton_OFF 0x3E8u
#define PK_TMainForm_BackButton_OFF 0x3ECu
#define PK_TMainForm_CopyFigureButton_OFF 0x3F0u
#define PK_TMainForm_PasteFigureButton_OFF 0x3F4u
#define PK_TMainForm_CopySelFrameButton_OFF 0x3F8u
#define PK_TMainForm_PasteFrameButton_OFF 0x3FCu
#define PK_TMainForm_PlayButton_OFF 0x400u
#define PK_TMainForm_StopButton_OFF 0x404u
#define PK_TMainForm_RepeatCheckBox_OFF 0x408u
#define PK_TMainForm_PopupMenu1_OFF 0x40Cu
#define PK_TMainForm_Insert1_OFF 0x410u
#define PK_TMainForm_InsertPaste1_OFF 0x414u
#define PK_TMainForm_Delete1_OFF 0x418u
#define PK_TMainForm_SaveSelected1_OFF 0x41Cu
#define PK_TMainForm_MultiSelect1_OFF 0x420u
#define PK_TMainForm_SelectBoxTimer_OFF 0x424u
#define PK_TMainForm_OpenDialog1_OFF 0x428u
#define PK_TMainForm_SaveDialog1_OFF 0x42Cu
#define PK_TMainForm_DoubleClickTimer_OFF 0x430u
#define PK_TMainForm_StyleBook1_OFF 0x434u
#define PK_TMainForm_ExportDialog_OFF 0x438u
#define PK_TMainForm_NextFrameRect_OFF 0x43Cu
#define PK_TMainForm_BackgroundRect_OFF 0x440u
#define PK_TMainForm_AddFigureRect_OFF 0x444u
#define PK_TMainForm_JoinRect_OFF 0x448u
#define PK_TMainForm_BatchLoadSaveStk_OFF 0x44Cu
#define PK_TMainForm_TextMenuItem_OFF 0x450u
#define PK_TMainForm_BackgroundColor1_OFF 0x454u
#define PK_TMainForm_MenuItem2_OFF 0x458u
#define PK_TMainForm_SelectBox_OFF 0x45Cu
#define PK_TMainForm_View1_OFF 0x460u
#define PK_TMainForm_Z100MenuItem_OFF 0x464u
#define PK_TMainForm_Z200MenuItem_OFF 0x468u
#define PK_TMainForm_ZSelMenuItem_OFF 0x46Cu
#define PK_TMainForm_ZAnimMenuItem_OFF 0x470u
#define PK_TMainForm_ZInMenuItem_OFF 0x474u
#define PK_TMainForm_ZOutMenuItem_OFF 0x478u
#define PK_TMainForm_Z50MenuItem_OFF 0x47Cu
#define PK_TMainForm_MenuItem9_OFF 0x480u
#define PK_TMainForm_ShowHandlesMenuItem_OFF 0x484u
#define PK_TMainForm_ScaleEdit_OFF 0x488u
#define PK_TMainForm_ShowCamMenuItem_OFF 0x48Cu
#define PK_TMainForm_ResetCamMenuItem_OFF 0x490u
#define PK_TMainForm_MenuItem1_OFF 0x494u
#define PK_TMainForm_ZCamMenuItem_OFF 0x498u
#define PK_TMainForm_StatusBar_OFF 0x49Cu
#define PK_TMainForm_FigureStatus_OFF 0x4A0u
#define PK_TMainForm_ZoomLabel_OFF 0x4A4u
#define PK_TMainForm_FrameStatus_OFF 0x4A8u
#define PK_TMainForm_SegmentStatus_OFF 0x4ACu
#define PK_TMainForm_ZoomRectangle_OFF 0x4B0u
#define PK_TMainForm_CloseTimer_OFF 0x4B4u
#define PK_TMainForm_AnimatedPng1_OFF 0x4B8u
#define PK_TMainForm_ExportTestItem_OFF 0x4BCu
#define PK_TMainForm_CopyCamMenuItem_OFF 0x4C0u
#define PK_TMainForm_PasteCamMenuItem_OFF 0x4C4u
#define PK_TMainForm_RecentMenuItem_OFF 0x4C8u
#define PK_TMainForm_RecentMenuItem0_OFF 0x4CCu
#define PK_TMainForm_RecentMenuItem1_OFF 0x4D0u
#define PK_TMainForm_RecentMenuItem2_OFF 0x4D4u
#define PK_TMainForm_RecentMenuItem3_OFF 0x4D8u
#define PK_TMainForm_RecentMenuItem4_OFF 0x4DCu
#define PK_TMainForm_RecentMenuItem5_OFF 0x4E0u
#define PK_TMainForm_RecentMenuItem6_OFF 0x4E4u
#define PK_TMainForm_RecentMenuItem7_OFF 0x4E8u
#define PK_TMainForm_RecentMenuItem8_OFF 0x4ECu
#define PK_TMainForm_RecentMenuItem9_OFF 0x4F0u
#define PK_TMainForm_SegmentInputMenuItem_OFF 0x4F4u
#define PK_TMainForm_DownloadFigMenuItem_OFF 0x4F8u
#define PK_TMainForm_PlayZoomMenuItem_OFF 0x4FCu
#define PK_TMainForm_SaveV4MenuItem_OFF 0x500u
#define PK_TMainForm_Deleteunusedfiguretypes1_OFF 0x504u
#define PK_TMainForm_DragDropTimer_OFF 0x508u
#define PK_TMainForm_ResetPoseMenuItem_OFF 0x50Cu
#define PK_TMainForm_ImportSVGMenuItem_OFF 0x510u
#define PK_TMainForm_AlignCamMenuItem_OFF 0x514u
#define PK_TMainForm_ApplyCamMenuItem_OFF 0x518u
#define PK_TMainForm_CenterCamFigsMenuItem_OFF 0x51Cu
#define PK_TMainForm_StyleBookDark_OFF 0x520u
#define PK_TMainForm_ImageListColor_OFF 0x524u
#define PK_TMainForm_InsertTweenMenuItem_OFF 0x528u
#define PK_TMainForm_CamCenterXItem_OFF 0x52Cu
#define PK_TMainForm_CamCenterYItem_OFF 0x530u
#define PK_TMainForm_CamCenterXYItem_OFF 0x534u
#define PK_TMainForm_EditModeMenuItem_OFF 0x538u
#define PK_TMainForm_RenameFigsMenuItem_OFF 0x53Cu
#define PK_TMultiLang_Def_OFF 0x4u
#define PK_TMultiLang_Phrases_OFF 0x8u
#define PK_TMultiLang_LangPath_OFF 0xCu
#define PK_TMultiLang_Lang_OFF 0x10u
#define PK_TPivotText_FChars_OFF 0x4u
#define PK_TPivotText_FPaths_OFF 0x8u
#define PK_TPivotText_FPathCount_OFF 0xCu
#define PK_TPivotText_FExtent_OFF 0x10u
#define PK_TPivotText_Layout_OFF 0x20u
#define PK_TIdxPolygon_FColor_OFF 0x4u
#define PK_TIdxPolygon_FTransparency_OFF 0x8u
#define PK_TIdxPolygon_FNumVertices_OFF 0xAu
#define PK_TIdxPolygon_VertexIdx_OFF 0xCu
#define PK_TIdxPolygon_DrawOrderIdx_OFF 0x10u
#define PK_TTrackBarLabel_FLabel_OFF 0x428u
#define PK_TTrackBarLabel_FSuffix_OFF 0x42Cu
#define PK_TTrackBarLabel_FTimer_OFF 0x430u
#define PK_TTrackBarLabel_FOffset_OFF 0x434u
#define PK_TTrackBarLabel_FValueToString_OFF 0x438u
#define PK_TVideoForm_ExportButton_OFF 0x2F8u
#define PK_TVideoForm_SpinBox1_OFF 0x2FCu
#define PK_TVideoForm_Button2_OFF 0x300u
#define PK_TVideoForm_FFEncoder_OFF 0x304u
#define PK_TVideoForm_FrameInputAdapter_OFF 0x308u
#define PK_TVideoForm_Label1_OFF 0x30Cu
#define PK_TVideoForm_LoopCheckBox_OFF 0x310u
#define PK_TVideoForm_DitherCheckBox_OFF 0x314u
#define PK_TVideoForm_HelpLabel_OFF 0x318u
#define PK_TVideoForm_CodecComboBox_OFF 0x31Cu
#define PK_TVideoForm_BitrateNumberBox_OFF 0x320u
#define PK_TVideoForm_BitrateLabel_OFF 0x324u
#define PK_TVideoForm_CompressCheckBox_OFF 0x328u
#define PK_TVideoForm_SmoothComboBox_OFF 0x32Cu
#define PK_TWavePlayer_FQueueThread_OFF 0x4u
#define PK_TWavePlayer_FPaused_OFF 0x8u
#define PK_TWavePlayer_FReadBuffer_OFF 0xCu
#define PK_TWavePlayer_FUserData_OFF 0x10u
#define PK_TWavePlayer_FLastErrMsg_OFF 0x14u
#define PK_TWavePlayer_FWaveHandle_OFF 0x18u
#define PK_TWavePlayer_FWaveFormat_OFF 0x1Cu
#define PK_TWavePlayer_FWaveHdr_OFF 0x30u
#define PK_TWavePlayer_FWaveBuf_OFF 0x34u
#define PK_TWavePlayer_FWaveBufSize_OFF 0x38u
#define PK_TWavePlayer_FWaveBufIdx_OFF 0x3Cu

/* ---- Published method addresses (form classes) ---- */
#define PK_TBackgroundColorForm_FormCreate_VA 0xA6EB64u
#define PK_TBackgroundColorForm_RadioButton12Change_VA 0xA6F638u
#define PK_TBackgroundColorForm_RadioButtonSolidChange_VA 0xA6F580u
#define PK_TBackgroundColorForm_TrackBarOffsetTracking_VA 0xA6FD10u
#define PK_TBackgroundColorForm_ColorButton1Click_VA 0xA6F4C0u
#define PK_TBackgroundColorForm_ColorButton2Click_VA 0xA6F520u
#define PK_TBackgroundColorForm_ColorButton1Change_VA 0xA6F434u
#define PK_TBackgroundColorForm_ColorButton2Change_VA 0xA6F480u
#define PK_TBackgroundColorForm_FormShow_VA 0xA6F318u
#define PK_TBackgroundColorForm_HelpLabelClick_VA 0xA6F3B4u
#define PK_TBackgroundColorForm_FormKeyDown_VA 0xA6EE9Cu
#define PK_TBackgroundColorForm_SwapButtonClick_VA 0xA6F2E4u
#define PK_TColorForm_ColorPanel1Change_VA 0xA636C4u
#define PK_TColorForm_FormCreate_VA 0xA62E7Cu
#define PK_TColorForm_ColorClick_VA 0xA6339Cu
#define PK_TColorForm_RGBSpinBoxChange_VA 0xA63514u
#define PK_TColorForm_HSLSpinBoxChange_VA 0xA6357Cu
#define PK_TColorForm_HexEditValidate_VA 0xA63618u
#define PK_TColorForm_AddButtonClick_VA 0xA63350u
#define PK_TColorForm_PickButtonClick_VA 0xA638CCu
#define PK_TColorForm_FormShow_VA 0xA63214u
#define PK_TColorForm_FormKeyDown_VA 0xA63200u
#define PK_TFigureBuilderForm_Initialize_VA 0xB07084u
#define PK_TFigureBuilderForm_FormCreate_VA 0xB06684u
#define PK_TFigureBuilderForm_EnableSelectedSegmentButtons_VA 0xB08D64u
#define PK_TFigureBuilderForm_SetSelectedObject_VA 0xB0BE5Cu
#define PK_TFigureBuilderForm_InitUndo_VA 0xB0D5B0u
#define PK_TFigureBuilderForm_MoveUndos_VA 0xB0D748u
#define PK_TFigureBuilderForm_AssignUndo_VA 0xB0D788u
#define PK_TFigureBuilderForm_Undo1Click_VA 0xB0DB1Cu
#define PK_TFigureBuilderForm_Redo1Click_VA 0xB0DEC4u
#define PK_TFigureBuilderForm_DisplaySegmentData_VA 0xB0B398u
#define PK_TFigureBuilderForm_EnableOutlineControls_VA 0xB0E644u
#define PK_TFigureBuilderForm_EraseFigure_VA 0xB073A8u
#define PK_TFigureBuilderForm_DrawFigure_VA 0xB07598u
#define PK_TFigureBuilderForm_DrawHandles_VA 0xB07A58u
#define PK_TFigureBuilderForm_EraseDraw_VA 0xB07CB0u
#define PK_TFigureBuilderForm_Image1MouseDown_VA 0xB07CF8u
#define PK_TFigureBuilderForm_Image1MouseUp_VA 0xB084C8u
#define PK_TFigureBuilderForm_Image1MouseMove_VA 0xB086ACu
#define PK_TFigureBuilderForm_DrawGeneralSegment_VA 0xB0C088u
#define PK_TFigureBuilderForm_StoreFigTypeAttributes_VA 0xB0A484u
#define PK_TFigureBuilderForm_FormResize_VA 0xB09E50u
#define PK_TFigureBuilderForm_FormHide_VA 0xB0C5F0u
#define PK_TFigureBuilderForm_FormShow_VA 0xB0D440u
#define PK_TFigureBuilderForm_DragTimerTimer_VA 0xB0875Cu
#define PK_TFigureBuilderForm_CircleButtonClick_VA 0xB0C1FCu
#define PK_TFigureBuilderForm_LineButtonClick_VA 0xB0C1F4u
#define PK_TFigureBuilderForm_btnPolyClick_VA 0xB0F5A0u
#define PK_TFigureBuilderForm_ChangeKindButtonClick_VA 0xB08F60u
#define PK_TFigureBuilderForm_DuplicateButtonClick_VA 0xB09120u
#define PK_TFigureBuilderForm_SplitButtonClick_VA 0xB0943Cu
#define PK_TFigureBuilderForm_DeleteButtonClick_VA 0xB09578u
#define PK_TFigureBuilderForm_ChangeStaticButtonClick_VA 0xB09918u
#define PK_TFigureBuilderForm_NominateButtonClick_VA 0xB09A0Cu
#define PK_TFigureBuilderForm_CircleKindButtonClick_VA 0xB09B70u
#define PK_TFigureBuilderForm_UpDownButtonMouseDown_VA 0xB0AC88u
#define PK_TFigureBuilderForm_UpDownButtonMouseUp_VA 0xB0AD30u
#define PK_TFigureBuilderForm_UpDownTimerTimer_VA 0xB0AD48u
#define PK_TFigureBuilderForm_ChangeThickness_VA 0xB0AD68u
#define PK_TFigureBuilderForm_ColorButtonClick_VA 0xB0AEB4u
#define PK_TFigureBuilderForm_OrderButtonClick_VA 0xB0B254u
#define PK_TFigureBuilderForm_ChangeSegOrder_VA 0xB0B260u
#define PK_TFigureBuilderForm_btnFlipClick_VA 0xB0F450u
#define PK_TFigureBuilderForm_New1Click_VA 0xB0AB94u
#define PK_TFigureBuilderForm_Open1Click_VA 0xB0A5F0u
#define PK_TFigureBuilderForm_OpenFigure_VA 0xB0A820u
#define PK_TFigureBuilderForm_Save1Click_VA 0xB0AAE4u
#define PK_TFigureBuilderForm_SaveAs1Click_VA 0xB0A0FCu
#define PK_TFigureBuilderForm_SaveFigureTypeAs_VA 0xB0A3A8u
#define PK_TFigureBuilderForm_AddToAnimation1Click_VA 0xB0BA9Cu
#define PK_TFigureBuilderForm_AddFigureType_VA 0xB0BC44u
#define PK_TFigureBuilderForm_EditFigureType1Click_VA 0xB0E6C0u
#define PK_TFigureBuilderForm_LoadSpriteImage1Click_VA 0xB0F12Cu
#define PK_TFigureBuilderForm_Exit1Click_VA 0xB0A080u
#define PK_TFigureBuilderForm_Outlinethicknessup1Click_VA 0xB0E4C8u
#define PK_TFigureBuilderForm_Outlinethicknessdown1Click_VA 0xB0E51Cu
#define PK_TFigureBuilderForm_OutlineColour1Click_VA 0xB0E590u
#define PK_TFigureBuilderForm_EditMode1Click_VA 0xB09D88u
#define PK_TFigureBuilderForm_FormKeyDown_VA 0xB0C710u
#define PK_TFigureBuilderForm_FormKeyUp_VA 0xB0D258u
#define PK_TFigureBuilderForm_HighlightBranch_VA 0xB0D14Cu
#define PK_TFigureBuilderForm_HighlightTimerTimer_VA 0xB0D250u
#define PK_TFigureBuilderForm_Duplicateflip1Click_VA 0xB09150u
#define PK_TFigureBuilderForm_Transparent1Click_VA 0xB0E1C8u
#define PK_TFigureBuilderForm_MenuBarMouseDown_VA 0xB0E394u
#define PK_TFigureBuilderForm_MenuBarMouseUp_VA 0xB0E3F0u
#define PK_TFigureBuilderForm_MenuBarMouseMove_VA 0xB0E460u
#define PK_TFigureBuilderForm_XButtonClick_VA 0xB0A0F4u
#define PK_TFigureBuilderForm_FormMouseWheel_VA 0xB0D380u
#define PK_TFigureBuilderForm_ZInMenuItemClick_VA 0xB0FB78u
#define PK_TFigureBuilderForm_ZOutMenuItemClick_VA 0xB0FBCCu
#define PK_TFigureBuilderForm_Z100MenuItemClick_VA 0xB0FC20u
#define PK_TFigureBuilderForm_Z200MenuItemClick_VA 0xB0FC54u
#define PK_TFigureBuilderForm_Z50MenuItemClick_VA 0xB0FC90u
#define PK_TFigureBuilderForm_ZSelMenuItemClick_VA 0xB0FD10u
#define PK_TFigureBuilderForm_ZFigMenuItemClick_VA 0xB0FF50u
#define PK_TFigureBuilderForm_ChangeCapButtonClick_VA 0xB09C78u
#define PK_TFigureBuilderForm_Gradient1Click_VA 0xB0AED8u
#define PK_TFigureBuilderForm_Help1Click_VA 0xB0FF84u
#define PK_TFigureBuilderForm_HighlightMenuItemClick_VA 0xB0D208u
#define PK_TFigureBuilderForm_FormDeactivate_VA 0xB0C70Cu
#define PK_TFigureBuilderForm_SegmentInputMenuItemClick_VA 0xB10018u
#define PK_TFigureBuilderForm_FormActivate_VA 0xB06674u
#define PK_TFigureBuilderForm_DoubleClickTimerTimer_VA 0xB0E380u
#define PK_TFigureBuilderForm_MatchZoomMenuItemClick_VA 0xB0E35Cu
#define PK_TFigureBuilderForm_UpdateTheme_VA 0xB10464u
#define PK_TFigureBuilderForm_BackColorMenuItemClick_VA 0xB108F0u
#define PK_TFigureBuilderForm_PreviewMenuItemClick_VA 0xB10A10u
#define PK_TFigureBuilderForm_ShowStaticMenuItemClick_VA 0xB0D110u
#define PK_TMainForm_TransScrollBarChange_VA 0xB248B8u
#define PK_TMainForm_RateScrollBarChange_VA 0xB2AF0Cu
#define PK_TMainForm_FormCreate_VA 0xB1B018u
#define PK_TMainForm_CreateStickmanType_VA 0xB1CE84u
#define PK_TMainForm_CreateFigureType1Click_VA 0xB29C78u
#define PK_TMainForm_SetFrameTween_VA 0xB2278Cu
#define PK_TMainForm_SetNumFrames_VA 0xB22940u
#define PK_TMainForm_PlayTimerTimer_VA 0xB2A9A8u
#define PK_TMainForm_StopButtonClick_VA 0xB2AD68u
#define PK_TMainForm_CheckUnstoredFrame_VA 0xB26300u
#define PK_TMainForm_SelectFrame_VA 0xB263ACu
#define PK_TMainForm_DrawFrameNumber_VA 0xB27618u
#define PK_TMainForm_IsFrameSelected_VA 0xB2773Cu
#define PK_TMainForm_GetFrameTween_VA 0xB2774Cu
#define PK_TMainForm_FormActivate_VA 0xB1BCE0u
#define PK_TMainForm_FormResize_VA 0xB1D8F8u
#define PK_TMainForm_NewProject_VA 0xB1C7C8u
#define PK_TMainForm_DestroyProject_VA 0xB1CA6Cu
#define PK_TMainForm_LoadProject_VA 0xB27B54u
#define PK_TMainForm_Undo1Click_VA 0xB2B6A8u
#define PK_TMainForm_Redo1Click_VA 0xB2B950u
#define PK_TMainForm_InitUndo_VA 0xB2B300u
#define PK_TMainForm_AssignUndo_VA 0xB2B45Cu
#define PK_TMainForm_EndDrag_VA 0xB20DFCu
#define PK_TMainForm_New1Click_VA 0xB2775Cu
#define PK_TMainForm_OpenAnimation1Click_VA 0xB27824u
#define PK_TMainForm_SetAnimationDimensions_VA 0xB29518u
#define PK_TMainForm_SetEditingArea_VA 0xB1DA34u
#define PK_TMainForm_SetScaleEditFromScale_VA 0xB24A38u
#define PK_TMainForm_SetFigureControls_VA 0xB24B18u
#define PK_TMainForm_SetFigureStatus_VA 0xB25468u
#define PK_TMainForm_SetFrameStatus_VA 0xB24FC0u
#define PK_TMainForm_SetSegmentStatus_VA 0xB257B8u
#define PK_TMainForm_SetFrameNumber_VA 0xB25B40u
#define PK_TMainForm_EnableFigureControls_VA 0xB25D6Cu
#define PK_TMainForm_IntToStr2_VA 0xB25CECu
#define PK_TMainForm_IntToStr3_VA 0xB25D24u
#define PK_TMainForm_SetEditFrame_VA 0xB1F16Cu
#define PK_TMainForm_FindOnions_VA 0xB1F3D4u
#define PK_TMainForm_Options1Click_VA 0xB2A3E4u
#define PK_TMainForm_FormClose_VA 0xB2A6D8u
#define PK_TMainForm_SaveProjectAsPiv_VA 0xB1CCBCu
#define PK_TMainForm_RemoveExtention_VA 0xB28C14u
#define PK_TMainForm_SaveAs1Click_VA 0xB28818u
#define PK_TMainForm_SetCursor_VA 0xB1CE30u
#define PK_TMainForm_Save1Click_VA 0xB28AE0u
#define PK_TMainForm_AddFigure_VA 0xB21DC0u
#define PK_TMainForm_DrawFigures_VA 0xB1F848u
#define PK_TMainForm_ReDrawFigure_VA 0xB1FD3Cu
#define PK_TMainForm_RecursiveReDraw_VA 0xB202B8u
#define PK_TMainForm_DrawAnimBorderLines_VA 0xB1D588u
#define PK_TMainForm_DrawGhostBackground_VA 0xB1D36Cu
#define PK_TMainForm_DrawGhost_VA 0xB1D0E4u
#define PK_TMainForm_DrawGhostEdit_VA 0xB1D1E8u
#define PK_TMainForm_EditingScrollBoxClick_VA 0xB20490u
#define PK_TMainForm_EditPaintBoxMouseDown_VA 0xB204A4u
#define PK_TMainForm_EditPaintBoxMouseUp_VA 0xB20920u
#define PK_TMainForm_EditPaintBoxMouseMove_VA 0xB21134u
#define PK_TMainForm_DoubleClickTimerTimer_VA 0xB20DE8u
#define PK_TMainForm_SelectBoxTimerTimer_VA 0xB21554u
#define PK_TMainForm_AddFigureButtonClick_VA 0xB218C4u
#define PK_TMainForm_BackgroundButtonClick_VA 0xB219C0u
#define PK_TMainForm_SetBackground_VA 0xB21A94u
#define PK_TMainForm_StoreEditedFrame_VA 0xB2228Cu
#define PK_TMainForm_NextFrameButtonClick_VA 0xB22034u
#define PK_TMainForm_FindSelectedFrameInList_VA 0xB26720u
#define PK_TMainForm_ToggleSelectedFrame_VA 0xB26760u
#define PK_TMainForm_Delete1Click_VA 0xB26898u
#define PK_TMainForm_Insert1Click_VA 0xB26F74u
#define PK_TMainForm_ShiftFrames_VA 0xB2D75Cu
#define PK_TMainForm_InsertPaste1Click_VA 0xB2BF00u
#define PK_TMainForm_SaveSelected1Click_VA 0xB26D60u
#define PK_TMainForm_MultiSelect1Click_VA 0xB27550u
#define PK_TMainForm_PopupMenu1Popup_VA 0xB275B0u
#define PK_TMainForm_DeleteSelFrameButtonClick_VA 0xB26B30u
#define PK_TMainForm_CopySelFrameButtonClick_VA 0xB26F64u
#define PK_TMainForm_PasteFrameButtonClick_VA 0xB2BEC4u
#define PK_TMainForm_PlayButtonClick_VA 0xB2A7E8u
#define PK_TMainForm_EnableControlsPlaying_VA 0xB2B168u
#define PK_TMainForm_DeleteFigureButtonClick_VA 0xB229FCu
#define PK_TMainForm_EditTypeButtonClick_VA 0xB23040u
#define PK_TMainForm_CenterButtonClick_VA 0xB23960u
#define PK_TMainForm_FlipButtonClick_VA 0xB23B34u
#define PK_TMainForm_ColorButtonClick_VA 0xB23CA4u
#define PK_TMainForm_OrderButtonClick_VA 0xB23F1Cu
#define PK_TMainForm_ChangeFigOrder_VA 0xB23F28u
#define PK_TMainForm_DuplicateFigures1Click_VA 0xB240CCu
#define PK_TMainForm_JoinButtonClick_VA 0xB24248u
#define PK_TMainForm_EditPaintBoxClick_VA 0xB1EE4Cu
#define PK_TMainForm_CopyFigureButtonClick_VA 0xB245A0u
#define PK_TMainForm_PasteFigureButtonClick_VA 0xB245FCu
#define PK_TMainForm_TransScrollBarTracking_VA 0xB24764u
#define PK_TMainForm_ScaleEditChange_VA 0xB23488u
#define PK_TMainForm_Export1Click_VA 0xB27F90u
#define PK_TMainForm_LoadBackground1Click_VA 0xB28CF0u
#define PK_TMainForm_LoadSprite1Click_VA 0xB29D6Cu
#define PK_TMainForm_LoadFigure1Click_VA 0xB2966Cu
#define PK_TMainForm_Exit1Click_VA 0xB2A3DCu
#define PK_TMainForm_SelectAll1Click_VA 0xB2A420u
#define PK_TMainForm_EditJoinedFigures1Click_VA 0xB2DD7Cu
#define PK_TMainForm_TweenToTimelineClick_VA 0xB2D8E0u
#define PK_TMainForm_SetNumTempFrames_VA 0xB2DCE0u
#define PK_TMainForm_ShowHandles1Click_VA 0xB2E154u
#define PK_TMainForm_SVG1Click_VA 0xB2BBF8u
#define PK_TMainForm_SVGnohandles1Click_VA 0xB2BCE8u
#define PK_TMainForm_SaveSVG_VA 0xB2BF28u
#define PK_TMainForm_NextFrameButtonMouseDown_VA 0xB2BDF4u
#define PK_TMainForm_Deletefiguresoutsidearea1Click_VA 0xB2CD84u
#define PK_TMainForm_BatchLoadSave1Click_VA 0xB2D334u
#define PK_TMainForm_BatchLoadSaveStkClick_VA 0xB2D4F8u
#define PK_TMainForm_FormMouseWheel_VA 0xB1DB34u
#define PK_TMainForm_FormKeyDown_VA 0xB1DD4Cu
#define PK_TMainForm_FormKeyUp_VA 0xB1ECD8u
#define PK_TMainForm_EditImageMouseEnter_VA 0xB1EE3Cu
#define PK_TMainForm_EditImageMouseLeave_VA 0xB1EE44u
#define PK_TMainForm_PivotHelp1Click_VA 0xB2A498u
#define PK_TMainForm_ViewReadMeFile1Click_VA 0xB2A518u
#define PK_TMainForm_About1Click_VA 0xB2A658u
#define PK_TMainForm_DragTimerTimer_VA 0xB211F8u
#define PK_TMainForm_TextMenuItemClick_VA 0xB29D48u
#define PK_TMainForm_BackgroundColor1Click_VA 0xB291C8u
#define PK_TMainForm_ZoomChange_VA 0xB2DDECu
#define PK_TMainForm_ZInMenuItemClick_VA 0xB2DEACu
#define PK_TMainForm_ZOutMenuItemClick_VA 0xB2DF08u
#define PK_TMainForm_Z100MenuItemClick_VA 0xB2DF64u
#define PK_TMainForm_Z200MenuItemClick_VA 0xB2DFA0u
#define PK_TMainForm_Z50MenuItemClick_VA 0xB2DFE4u
#define PK_TMainForm_ZSelMenuItemClick_VA 0xB2E028u
#define PK_TMainForm_ZAnimMenuItemClick_VA 0xB2E07Cu
#define PK_TMainForm_ShowCamMenuItemClick_VA 0xB2E190u
#define PK_TMainForm_ResetCamMenuItemClick_VA 0xB2E1DCu
#define PK_TMainForm_ZCamMenuItemClick_VA 0xB2E0DCu
#define PK_TMainForm_ExportTestItemClick_VA 0xB287A0u
#define PK_TMainForm_EnableControlsExport_VA 0xB285E4u
#define PK_TMainForm_CopyCamMenuItemClick_VA 0xB2E2C4u
#define PK_TMainForm_PasteCamMenuItemClick_VA 0xB2E3B0u
#define PK_TMainForm_RecentMenuItemClick_VA 0xB2F1B0u
#define PK_TMainForm_SegmentInputMenuItemClick_VA 0xB2F33Cu
#define PK_TMainForm_DownloadFigMenuItemClick_VA 0xB2A670u
#define PK_TMainForm_PlayZoomMenuItemClick_VA 0xB2E128u
#define PK_TMainForm_RepeatCheckBoxChange_VA 0xB2AEF4u
#define PK_TMainForm_SaveV4MenuItemClick_VA 0xB2BDD8u
#define PK_TMainForm_TweenSpinEditChange_VA 0xB22734u
#define PK_TMainForm_Deleteunusedfiguretypes1Click_VA 0xB2CFB0u
#define PK_TMainForm_ScaleEditKeyDown_VA 0xB23640u
#define PK_TMainForm_DragDropTimerTimer_VA 0xB2FEB0u
#define PK_TMainForm_AlignCanvases_VA 0xB2EC04u
#define PK_TMainForm_RestoreCanvasZoom_VA 0xB2EE5Cu
#define PK_TMainForm_FormDeactivate_VA 0xB1BCDCu
#define PK_TMainForm_ResetPoseMenuItemClick_VA 0xB241E8u
#define PK_TMainForm_ImportSVGMenuItemClick_VA 0xB2FEF8u
#define PK_TMainForm_AlignCamMenuItemClick_VA 0xB2E62Cu
#define PK_TMainForm_ApplyCamMenuItemClick_VA 0xB2E848u
#define PK_TMainForm_CenterCamFigsMenuItemClick_VA 0xB2E904u
#define PK_TMainForm_UpdateTheme_VA 0xB30198u
#define PK_TMainForm_ScaleEditMouseWheel_VA 0xB235CCu
#define PK_TMainForm_InsertTweenMenuItemClick_VA 0xB26FF8u
#define PK_TMainForm_EditModeMenuItemClick_VA 0xB30A18u
#define PK_TMainForm_RenameFigsMenuItemClick_VA 0xB2D5D8u
#define PK_TVideoForm_Button2Click_VA 0xADEA3Cu
#define PK_TVideoForm_SpinBox1Enter_VA 0xADEA54u
#define PK_TVideoForm_ExportButtonClick_VA 0xADCFACu
#define PK_TVideoForm_FrameInputAdapterReadFrameCanvas_VA 0xADDF68u
#define PK_TVideoForm_FFEncoderTerminate_VA 0xADE138u
#define PK_TVideoForm_FFEncoderProgress_VA 0xADE0E4u
#define PK_TVideoForm_FormCreate_VA 0xADE2F8u
#define PK_TVideoForm_FormShow_VA 0xADE41Cu
#define PK_TVideoForm_HelpLabelClick_VA 0xADDDDCu
#define PK_TVideoForm_CodecComboBoxChange_VA 0xADCF18u
#define PK_TVideoForm_FormKeyDown_VA 0xADE408u

#endif /* PIVOT_5_2_11_BINDINGS_H */
