#!/usr/bin/env python3
"""Generate C bindings from research/mappings/classes_full.json.

Output: include/pivot/pivot_5_2_11.h  (single self-contained header)

The header exposes:
  * PkClassInfo tables (VMT VA, instance size, parent, unit) for app classes
  * struct definitions for classes with full init-table field maps
  * offset macros for every field (name-based access even without structs)
  * published-method address macros for form classes

Everything is generated from the RE database; do not hand-edit the output.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DB = os.path.join(HERE, "..", "research", "mappings", "classes_full.json")
OUT = os.path.join(HERE, "..", "include", "pivot", "pivot_5_2_11.h")

APP_UNITS = {
    "MainUnit", "FigureUnit", "FiguresUnit", "FigureTypeUnit", "GlobalTypes",
    "PlayerUnit", "SpriteUnit", "PolygonUnit", "PivotTextUnit", "WavePlay",
    "WinBitmap", "ThreadedTimer", "MultiLanguage", "ZoomImageUnit",
    "ImageSelector", "VideoUnit", "AVICompression", "FigureBuilderUnit",
    "ColorUnit", "BackgroundColorUnit", "LabelBackUnit", "TrackBarLabelUnit",
}

# form classes with published methods worth exporting
FORM_CLASSES = {
    "TMainForm", "TFigureBuilderForm", "TTextForm", "TVideoForm",
    "TBackgroundColorForm", "TColorForm", "TSpriteForm", "TFrameInsertForm",
    "TFigureSelectorForm",
}


def ctype_for(t):
    if not t:
        return "uint32_t"
    s = str(t)
    if "Single" in s or "Float" in s:
        return "float"
    if "TRectF" in s:
        return "PkRectF"
    if "TRect" in s:
        return "PkRect"
    if "TCamera" in s:
        return "PkCamera"
    if "TAttachment" in s:
        return "PkAttachment"
    if "DynArray" in s or "TArray" in s:
        return "PkDynArray"
    if "Boolean" in s:
        return "uint8_t"
    if "TAlphaColor" in s or s == "Integer":
        return "uint32_t"
    return "uint32_t"



def ctype_sized(t, size):
    """Pick a C type whose width matches the inferred field size."""
    ts = str(t or "")
    if "Boolean" in ts:
        return "uint8_t"
    if "TRectF" in ts:
        return "PkRectF"
    if "TRect" in ts:
        return "PkRect"
    if "TCamera" in ts:
        return "PkCamera"
    if "TAttachment" in ts:
        return "PkAttachment"
    if "TPointF" in ts:
        return "PkPoint"
    if "Double" in ts:
        return "double"
    if "Single" in ts or "Float" in ts:
        return "float"
    if "DynArray" in ts or "TArray" in ts:
        return "PkDynArray"
    return {1: "uint8_t", 2: "uint16_t", 8: "uint64_t"}.get(size, "uint32_t")

def cident(s):
    s = re.sub(r"[^A-Za-z0-9_]", "_", s)
    if s and s[0].isdigit():
        s = "_" + s
    return s


def main():
    db = json.load(open(DB, encoding="utf-8"))
    classes = db["classes"]
    by_name = {c["name"]: c for c in classes}
    app = [c for c in classes if c.get("unit") in APP_UNITS]
    app.sort(key=lambda c: (c.get("unit") or "", c["name"]))

    h = []
    w = h.append
    w("/* Generated by tools/gen_bindings.py from the PivotKit RE database.")
    w(" * Target: Pivot Animator 5.2.11 (sha256 2c7911d3303cc28d...).")
    w(" * DO NOT EDIT BY HAND - edit the database/research and regenerate. */")
    w("#ifndef PIVOT_5_2_11_BINDINGS_H")
    w("#define PIVOT_5_2_11_BINDINGS_H")
    w("#include <stdint.h>")
    w("")
    w("#define PIVOT_IMAGE_BASE 0x400000u")
    w("")
    w("typedef struct PkRect   { int32_t l, t, r, b; } PkRect;")
    w("typedef struct PkRectF  { float   l, t, r, b; } PkRectF;")
    w("typedef struct PkPoint  { float   x, y; } PkPoint;")
    w("/* TCamera (GlobalTypes) - exact member layout TBD */")
    w("typedef struct PkCamera { PkPoint pos; float angle; } PkCamera;")
    w("/* TAttachment (GlobalTypes) - 6 bytes; exact layout TBD */")
    w("typedef struct PkAttachment { uint8_t raw[6]; } PkAttachment;")
    w("/* Delphi dynamic array: ptr-4 = length (elements), ptr-8 = refcount */")
    w("typedef struct PkDynArray { void *data; } PkDynArray;")
    w("static inline uint32_t pk_dynarray_len(const PkDynArray *a) {")
    w("    return a->data ? *(uint32_t *)((char *)a->data - 4) : 0; }")
    w("")

    w("/* ---- Class registry (VMT addresses, instance sizes) ---- */")
    w("typedef struct PkClassInfo {")
    w("    const char *name;")
    w("    const char *unit;")
    w("    const char *parent;")
    w("    uint32_t    vmt_va;")
    w("    uint32_t    instance_size;")
    w("} PkClassInfo;")
    w("")
    w("static const PkClassInfo PkClasses[] = {")
    for c in app:
        w(f'    {{ "{c["name"]}", "{c.get("unit")}", '
          f'"{c.get("parent") or ""}", 0x{c["classtype_va"]:X}u, '
          f'0x{c["instance_size"]:X}u }},')
    w("};")
    w("#define PkClassCount (sizeof(PkClasses)/sizeof(PkClasses[0]))")
    w("")

    w("/* ---- Structs for classes with init-table field maps ---- */")
    pad_i = 0
    w("#pragma pack(push, 1)  /* offsetof must equal the RE offsets */")
    for c in app:
        tf = c.get("typed_fields") or []
        if not tf:
            continue
        w(f"/* {c['name']} ({c.get('unit')}) - VMT 0x{c['classtype_va']:X}, "
          f"size 0x{c['instance_size']:X} */")
        w(f"typedef struct {cident(c['name'])}S {{")
        w("    uint32_t vmt; /* +0x00 */")
        prev_end = 4
        offs = [int(f["offset"]) for f in tf]
        for fi, f in enumerate(tf):
            off = offs[fi]
            if off < prev_end:
                continue  # aliased view of earlier storage
            if off > prev_end:
                pad_i += 1
                w(f"    uint8_t _pad{pad_i}_{prev_end:X}[0x{off:X} - 0x{prev_end:X}];")
            t = str(f.get("type") or "")
            base = 4
            if "Boolean" in t:
                base = 1
            elif "TRectF" in t or "TRect" in t:
                base = 16
            elif "TCamera" in t:
                base = 12
            elif "TAttachment" in t:
                base = 6
            elif "Double" in t or "TPointF" in t:
                base = 8
            nxt = offs[fi + 1] if fi + 1 < len(offs) else (c["instance_size"] or off + base)
            gap = nxt - off
            size = base if gap <= 0 or gap >= base else gap
            w(f"    {ctype_sized(t, size)} {cident(f['name'])};"
              f" /* +0x{off:X} : {f.get('type')} */")
            prev_end = off + size
        if c["instance_size"] > prev_end:
            w(f"    uint8_t _tail[{c['instance_size'] - prev_end}];")
        w(f"}} {cident(c['name'])}S;")
        w("")

    w("/* ---- Record layouts (from tkRecord TypeInfos) ---- */")
    pad_i = 0
    for r in db.get("records", []):
        nm = cident(r["name"]) + "Rec"
        w(f"/* {r['name']} - {r['recsize']} bytes */")
        w(f"typedef struct {nm}S {{")
        prev = 0
        offs = [int(f["offset"]) for f in r["fields"]]
        for fi, f in enumerate(r["fields"]):
            off = offs[fi]
            if off < prev:
                continue  # union-style alias member (same storage, later view)
            if off > prev:
                pad_i += 1
                w(f"    uint8_t _pad{pad_i}_{prev:X}[0x{off:X} - 0x{prev:X}];")
            t = str(f.get("type") or "")
            base = 4
            if "Boolean" in t:
                base = 1
            elif "Double" in t:
                base = 8
            elif "TPointF" in t:
                base = 8
            elif "Single" in t or "Float" in t:
                base = 4
            nxt = offs[fi + 1] if fi + 1 < len(offs) else r["recsize"]
            gap = nxt - off
            size = base if gap <= 0 or gap >= base else gap
            w(f"    {ctype_sized(t, size)} {cident(f['name'])}; /* +0x{off:X} : {f.get('type')} */")
            prev = off + size
        if r["recsize"] > prev:
            w(f"    uint8_t _tail[{r['recsize'] - prev}];")
        w(f"}} {nm}S;")
        w("")

    w("#pragma pack(pop)")

    w("/* ---- Field offset macros (name -> offset, all mapped classes) ---- */")
    for c in app:
        for f in (c.get("typed_fields") or []) + (c.get("published_fields") or []):
            nm = f["name"]
            if "offset" not in f:
                continue
            w(f"#define PK_{cident(c['name'])}_{cident(nm)}_OFF 0x{int(f['offset']):X}u")
    w("")

    w("/* ---- Published method addresses (form classes) ---- */")
    for c in app:
        if c["name"] not in FORM_CLASSES:
            continue
        for m in c.get("published_methods") or []:
            w(f"#define PK_{cident(c['name'])}_{cident(m['name'])}_VA 0x{m['va']:X}u")
    w("")
    w("#endif /* PIVOT_5_2_11_BINDINGS_H */")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(h) + "\n")
    print(f"[+] wrote {OUT} ({len(h)} lines, {len(app)} app classes)")


if __name__ == "__main__":
    main()
